export default{
    orient:[{
        label:'横向',
        value:'horizontal'
      },
      {
        label:'竖向',
        value:'vertical'
      }],
    align:[{
        label:'自动',
        value:'auto'
      },
      {
        label:'左对齐',
        value:'left'
      },
      {
        label:'右对齐',
        value:'right'
      }],
    nameLocation:[
          {
              label:'起始位置',
              value:'start'
          },{
              label:'中间',
              value:'center'
          },{
              label:'末尾',
              value:'end'
          }
      ],
      type:[
        {
            label:'类目轴',
            value:'category'
        },{
            label:'数值轴',
            value:'value'
        },{
            label:'时间轴',
            value:'time'
        },{
            label:"对数轴",
            value:'log'
        }
      ],
      trigger:[
        {
            label:'坐标轴触发',
            value:'axis'
        },{
            label:'数据项图形触发',
            value:'item'
        },{
            label:'什么都不触发',
            value:'none'
        }
      ],
      triggerOn:[
        {
            label:'鼠标移动时触发',
            value:'mousemove'
        },{
            label:'鼠标点击时触发',
            value:'click'
        },{
            label:'以上两者同时触发',
            value:'mousemove|click'
        },{
            label:"不触发",
            value:'none'
        }
      ],

}