export default{
    types:[//所有支持的图标类型
       {
        name:'折线统计图',
        value:'line',
        img:''
       },{
           name:'条形统计图',
           value:'bar',
           img:''
       },{
           name:'饼图',
           value:'pie',
           img:''
       }
    ],
     optionName:{
        title:{
            name:"标题",
            support:'ALL'
        },
        legend:{
            name:"图例",
            support:"ALL"
        },
        grid:{
            name:'坐标网格',
            support:['line','bar']
        }
    }
}